### ISSUE TITLE
Consulting?

### ISSUE THREAD

**Issue by d1rewolf** [mikepotjer/vfp-git-utils#14]
Hi Mike.

I tried your email found in the git logs, but it was returned.

Are you available for consulting work? I'd be very interested in having a discussion with you if so.

Thanks!

**Comment by mikepotjer** [comment]
Hi John,

 

Thank you for your interest, but I’m plenty busy with my day job, and I don’t really have the time or desire to take on extra work. Sorry. If you haven’t already come across Rick Schummer, I highly recommend him: http://www.whitelightcomputing.com/contactall.htm. That is a group of top-notch VFP developers.

 

All the best,

Mike

 

From: John Wells ***@***.***> 
Sent: Monday, October 10, 2022 9:51 PM
To: mikepotjer/vfp-git-utils ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mikepotjer/vfp-git-utils] Consulting? (Issue #14)

 

Hi Mike.

I tried your email found in the git logs, but it was returned.

Are you available for consulting work? I'd be very interested in having a discussion with you if so.

Thanks!

**Comment by d1rewolf** [comment]
Thanks Mike. What I'm most interested in is taking a FoxPro project stored in Visual SourceSafe and transitioning it to git. I'm not a FoxPro developer (I'm learning!) and have inherited a project. Are you aware of a guide for doing so? Or, do you think White Light can help with this? 

Thanks again.

**Comment by d1rewolf** [comment]
Thanks for your work on this Mike. I appreciate it.
