### ISSUE TITLE
Error Restore File TimeStamps

### ISSUE THREAD

**Issue by EdwardTheGreat** [mikepotjer/vfp-git-utils#2]
This error is very similar to one I reported with create time stamps

I believe this is how I encountered this problem.
1) Create file time stamps
2) Delete Some files
3) Commit/Push

On another machine 
1) pull and merge the changes.
2) Restore File TimeStamps

Because the file is in the time stamp file, but not on the local machine it causes an error.

FUNCTION RestoreRepoTimestamps
at the very end of the method

loFolderItem = m.loFolder.ParseName( m.lcFileName )    && returns .null.

IF NOT m.loFolderItem.ModifyDate = laFileDateList[m.lnRow, 2]  && throws the error

**Comment by mikepotjer** [comment]
Thanks Edward.

If you re-save the file timestamps before commit, the timestamps for the deleted files will be removed from the list.  Nevertheless, what you are reporting here is a bug.  Your description of the problem is just what I needed to reproduce it.
