### ISSUE TITLE
RestoreRepoTimestamps on Deleted Folder

### ISSUE THREAD

**Issue by EdwardTheGreat** [mikepotjer/vfp-git-utils#3]
I found another small thing that needs handling.
Just above the line where you handle if a file has been deleted, it also needs to handle if the folder has been deleted.   This is I handled it

```
FOR lnRow = 1 TO m.lnFileCount
    lcFileName = JUSTFNAME( laFileDateList[m.lnRow, 1] )
    *-- Get the full folder name and normalize it to backslashes.
    lcFolder = m.lcRepository + JUSTPATH( CHRTRAN( laFileDateList[m.lnRow, 1], "/", "\" ) )

    *-- Get a shell object reference to the file.
    loFolder = m.loShell.NameSpace( m.lcFolder )
    if !isnull(loFolder)            && efc 12/01/2015 added 
        loFolderItem = m.loFolder.ParseName( m.lcFileName )

        *-- If the current modification date of this file is different
        *-- from what was saved, replace it.
        if !isnull(loFolderItem)        && efc 11/15/2015 added 
            IF NOT m.loFolderItem.ModifyDate = laFileDateList[m.lnRow, 2]
                loFolderItem.ModifyDate = laFileDateList[m.lnRow, 2]
            ENDIF
        endif
    endif
```

**Comment by mikepotjer** [comment]
Hi Eddie,

It looks like you are referring to code in the RestoreRepoTimestamps()
method, but if so, you are still using the older version of the utilities.
I addressed that issue in the November 20 release of the Git Utilities.  If
you haven't installed the latest version, please do so and confirm if that
solves the problem.  Also, if your edited copy of
Thor_Proc_GitUtilities.PRG is in Thor's "My Tools" folder, you need to
delete or rename the .PRG and .FXP in that folder to ensure that you're
running the "official" version, and not your copy.

Thanks,
Mike

Mike Potjer

**Comment by EdwardTheGreat** [comment]
I downloaded the latest version now.  The issue is a bit complicated to replicate.

*-- Get a shell object reference to the file.
        loFolder = m.loShell.NameSpace( m.lcFolder )
        loFolderItem = m.loFolder.ParseName( m.lcFileName )

I am reasonably sure that if the folder is deleted then loFolder will return a .null. and cause an error on the 2nd line.

**Comment by mikepotjer** [comment]
In context, that code now looks like this:

![image](https://cloud.githubusercontent.com/assets/9847353/11514845/b010b8be-9848-11e5-8a42-0dd196831bc8.png)

So if folder has been deleted, the DIRECTORY() check will deal with that
before loShell.NameSpace() is called.  The GetRepoFileModifyDates() and
RestoreRepoTimestamps() methods both have such code.  If the error occurs
somewhere else, please let me know.

Thanks,

Mike Potjer

**Comment by mikepotjer** [comment]
It doesn't look like the image in my email came through on GitHub, so here it is:
![image](https://cloud.githubusercontent.com/assets/9847353/11514800/677e5d54-9848-11e5-8aa0-4da567c7c247.png)

**Comment by EdwardTheGreat** [comment]
Oh, duh, I did not see that.  Thanks!!

**Comment by mikepotjer** [comment]
No problem!  I just wanted to make sure I wasn't missing something.

Mike Potjer
