### ISSUE TITLE
Recursive folder handling

### ISSUE THREAD

**Issue by paulmrozowski** [mikepotjer/vfp-git-utils#5]
Is the "Prepare repository for commit" supposed to be able to handle folders recursively or does it only operate on the selected folder?

**Comment by mikepotjer** [comment]
Hi Paul,

Basically yes, all subfolders that are included in the repository are processed. You would select what I would call the root folder of a repository (the folder containing the hidden .git or .hg folder), then the utility prepares all files in that repository, wherever they are in the folder hierarchy.

**Comment by paulmrozowski** [comment]
Weird, it doesn't seem to be picking up all my subfolders even though they're part of the repo. I guess I'll have to trace through it to see why.

**Comment by paulmrozowski** [comment]
OK, so it appears like it only picks up files it thinks have changed via git status. These particular files haven't changed (this was an initial check-in), so it didn't generate them. I'll just manually generate them through FoxBin2PRG.

**Comment by mikepotjer** [comment]
I see. I didn't want this utility to assume you want to commit EVERY new file, so you do need to add files via git first, then run the prepare for commit tool.
Are you planning to commit VFP binaries, or just the FoxBin2Prg text files?

- When committing binaries, you need to at least add the main binary, then run the "prepare" process. For example, use git to mark a .SCX file as added, then run the prepare process. The utility will make sure the .SCT file is also added, and will run FoxBin2Prg to generate the .SC2 file. Then you can commit.
- When committing just the FoxBin2Prg text files, then you will need to run FoxBin2Prg directly the first time you want to add a file. Then add the text files and commit.

**Comment by mikepotjer** [comment]
I think your question is answered, and since there isn't a  specific request here, I am going to close this out. However, I did add issue #6 in response to this conversation.
